pipeline{
    agent any
    stages{
        stage("first"){
            steps{
                echo 'hello world'
            }

        }
        stage("run MyScanpy"){
            steps{
               bat "python hjt\\MyScanpy.py"
            }
        }

    }




}