pipeline{
    agent any
    stages{
        stage("first"){
            steps{
                echo 'hello world'
            }

        }
        stage("run MyScanpy"){
            steps{
                sh "pythons3 hjt/MyScanpy.py"
            }
        }

    }




}